version: '3.4'

services:
  server:
    build: .docker/nginx
    image: nginx
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT}:80
    networks:
      - backend

  app:
    build: .docker/php
    image: php:8
    volumes:
      - ./:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    ports:
      - ${DB_EXTERNAL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
